name: E2E Tests
on: push
  # pull_request:
  #   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 20
        - name: Install
          run: npm install
        - name : Build  
          run : npm run build 
        - name : Start 
          run : npm start 
        - name: Run Test
          run: npm run wdio
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs